CREATE TABLE phones (
    id INTEGER PRIMARY KEY NOT NULL, 
    manufacturer TEXT NOT NULL, 
    model TEXT NOT NULL, 
    price TEXT NOT NULL, 
    colors TEXT, 
    internal_memory_variants TEXT, 
    battery_capacity TEXT, 
    screen_size TEXT, 
    screen_technology TEXT, 
    resolution TEXT, 
    screen_refresh_rate TEXT, 
    ram_memory TEXT, 
    camera TEXT, 
    processor TEXT, 
    processor_speed TEXT, 
    processor_cores INTEGER, 
    operating_system TEXT, 
    connectivity TEXT, 
    dust_water_resistance_standard TEXT, 
    sim_card_type TEXT
);
